#ifndef __DISPLAY_COMMAND_TABLE_HELPER_DCE110_H__
#define __DISPLAY_COMMAND_TABLE_HELPER_DCE110_H__

struct command_table_helper;

const struct command_table_helper *display_cmd_tbl_helper_dce110_get_table(void);

#endif
